---
#####################################################################################################################
# Installation Variables
# should be set in your VAULT only. Check documentation.
#####################################################################################################################

splunk_auth:
  admin_password: "{{ vault_splunk_admin_password }}"
  splunk_secret: xxxxxxxxxxxxxxxxxx
