---
#####################################################################################################################
# Installation Variables
#####################################################################################################################

vmtools_installation:
  # set "type" to:
  # "rpm" -> if you want to install vmtools by RPM package
  # "skip" -> if you do not want to install vmware tools
  type: "skip"
  splunk_home_path: "{{ splunk_installation.splunk_home_path }}"
  package_format: rpm
  remote_package_temp_path: /tmp
  delete_package_after_install: true
  remote_app_temp_path: /tmp
