---
#####################################################################################################################
# Configurations for Splunk distsearch.conf
####################################################################################################################

# usually should not touched
splunk_distsearch_conf:
    distributedSearch:
      servers: 
        - "{{ groups.peernode }}"
